name: Good first issue proposal
description: Suggest a newcomer-friendly task
title: "[Good First Issue]: "
labels: ["good first issue"]
body:
  - type: textarea
    id: task
    attributes:
      label: Proposed task
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Why this is newcomer friendly
    validations:
      required: true
