from langchain_core.tools import BaseTool

from mia.integrations.convex import ConvexClient
from mia.tools.calendar import build_calendar_tools
from mia.tools.coding import CODING_TOOLS
from mia.tools.computer import build_computer_tools
from mia.tools.search import build_search_tools


AVAILABLE_TOOL_NAMES = {
    "list_calendar_events",
    "create_calendar_hold",
    "explain_code_request",
    "propose_test_cases",
    "update_plan",
    "session_status",
    "agents_list",
    "tools_inventory",
    "exec",
    "process",
    "read",
    "write",
    "edit",
    "apply_patch",
    "open_url",
    "open_app",
    "get_frontmost_app",
    "list_running_apps",
    "screenshot_desktop",
    "read_file",
    "list_directory",
    "file_info",
    "search_files",
    "write_file",
    "delete_file",
    "append_file",
    "replace_in_file",
    "create_directory",
    "copy_file",
    "move_file",
    "run_terminal_command",
    "process_start",
    "process_list",
    "process_read",
    "process_kill",
    "sessions_list",
    "sessions_history",
    "sessions_spawn",
    "sessions_send",
    "sessions_yield",
    "subagents",
    "gateway",
    "nodes",
    "canvas",
    "image_generate",
    "music_generate",
    "video_generate",
    "send_imessage",
    "message",
    "create_reminder",
    "cron",
    "click_screen",
    "type_text",
    "press_key",
    "scroll",
    "fetch_webpage",
    "web_fetch",
    "get_clipboard",
    "set_clipboard",
    "show_notification",
    "speak_text",
    "tts",
    "image_info",
    "image",
    "extract_pdf_text",
    "pdf",
    "web_search",
}


def tool_registry(
    convex: ConvexClient,
    *,
    source_message_handle: str,
    requester_number: str = "",
    run_id: str | None = None,
    searxng_base_url: str = "",
) -> dict[str, BaseTool]:
    tools: list[BaseTool] = [
        *build_calendar_tools(convex, source_message_handle=source_message_handle),
        *CODING_TOOLS,
        *build_computer_tools(
            convex,
            requester_number=requester_number,
            message_handle=source_message_handle,
            run_id=run_id,
        ),
        *build_search_tools(searxng_base_url=searxng_base_url),
    ]
    return {tool.name: tool for tool in tools}


def public_tool_descriptions() -> str:
    return "\n".join(
        [
            "- list_calendar_events: list Mia calendar holds for a day",
            "- create_calendar_hold: create a tentative calendar hold",
            "- explain_code_request: break down a programming request",
            "- propose_test_cases: propose focused tests for code work",
            "- update_plan: update Mia's lightweight task plan",
            "- session_status: inspect Mia's current agent-process status",
            "- agents_list: list Mia's built-in agent roles",
            "- tools_inventory: list registered dynamic sub-agent tool names",
            "- exec: OpenClaw-compatible alias for run_terminal_command",
            "- process: OpenClaw-compatible process manager alias",
            "- read: OpenClaw-compatible alias for read_file",
            "- write: OpenClaw-compatible alias for write_file",
            "- edit: OpenClaw-compatible alias for replace_in_file",
            "- apply_patch: request approval to apply a local workspace patch",
            "- open_url: open a safe http/https URL in the Mac browser; owner-only",
            "- open_app: request approval to open a macOS app",
            "- get_frontmost_app: inspect the currently active macOS app; owner-only",
            "- list_running_apps: list visible running macOS apps; owner-only",
            "- screenshot_desktop: capture the Mac desktop to a local PNG; owner-only",
            "- read_file: read a local text file",
            "- list_directory: list local files and directories under a path; owner-only",
            "- file_info: inspect local file or directory metadata; owner-only",
            "- search_files: search local file paths by name under a directory; owner-only",
            "- write_file: request approval to write a local file",
            "- delete_file: request approval to delete a local file",
            "- append_file: request approval to append text to a local file",
            "- replace_in_file: request approval to replace exact text inside a local file",
            "- create_directory: request approval to create a local directory",
            "- copy_file: request approval to copy a local file",
            "- move_file: request approval to move or rename a local file",
            "- run_terminal_command: request approval to run a terminal command",
            "- process_start: request approval to start a background shell process",
            "- process_list: list Mia-managed background processes; owner-only",
            "- process_read: read logs from a Mia-managed background process; owner-only",
            "- process_kill: request approval to terminate a Mia-managed background process",
            "- sessions_list: OpenClaw-compatible alias for process_list",
            "- sessions_history: OpenClaw-compatible session log history",
            "- sessions_spawn: request approval to spawn a managed shell session",
            "- sessions_send: send stdin to a managed shell session",
            "- sessions_yield: yield a message back to the parent agent",
            "- subagents: inspect Mia dynamic sub-agent surface",
            "- gateway: inspect Mia gateway heartbeat/status",
            "- nodes: inspect Mia node/gateway status",
            "- canvas: create a lightweight local Markdown canvas note",
            "- image_generate: OpenClaw-compatible image generation surface; provider required",
            "- music_generate: OpenClaw-compatible music generation surface; provider required",
            "- video_generate: OpenClaw-compatible video generation surface; provider required",
            "- send_imessage: request approval to send an outbound iMessage through SendBlue",
            "- message: OpenClaw-compatible alias for send_imessage",
            "- create_reminder: request approval to create a macOS Reminders reminder",
            "- cron: OpenClaw-compatible reminder scheduling alias",
            "- click_screen: request approval to click an absolute screen coordinate",
            "- type_text: request approval to type text into the active app",
            "- press_key: request approval to press a key with optional modifiers",
            "- scroll: request approval to scroll the active window",
            "- fetch_webpage: fetch a public http/https webpage and return text",
            "- web_fetch: OpenClaw-compatible alias for fetch_webpage",
            "- get_clipboard: read current clipboard text; owner-only",
            "- set_clipboard: request approval to replace clipboard text",
            "- show_notification: request approval to show a macOS notification",
            "- speak_text: request approval to speak text aloud using macOS say",
            "- tts: OpenClaw-compatible alias for speak_text",
            "- image_info: inspect local image metadata; owner-only",
            "- image: OpenClaw-compatible alias for image_info",
            "- extract_pdf_text: extract text from a local PDF when possible; owner-only",
            "- pdf: OpenClaw-compatible alias for extract_pdf_text",
            "- web_search: search the web using SearXNG",
        ]
    )


OWNER_ONLY_TOOLS = {
    "open_url",
    "open_app",
    "get_frontmost_app",
    "list_running_apps",
    "screenshot_desktop",
    "read_file",
    "list_directory",
    "file_info",
    "search_files",
    "write_file",
    "delete_file",
    "append_file",
    "replace_in_file",
    "create_directory",
    "copy_file",
    "move_file",
    "run_terminal_command",
    "process_start",
    "process_list",
    "process_read",
    "process_kill",
    "exec",
    "process",
    "read",
    "write",
    "edit",
    "apply_patch",
    "sessions_list",
    "sessions_history",
    "sessions_spawn",
    "sessions_send",
    "subagents",
    "gateway",
    "nodes",
    "canvas",
    "image_generate",
    "music_generate",
    "video_generate",
    "send_imessage",
    "message",
    "create_reminder",
    "cron",
    "click_screen",
    "type_text",
    "press_key",
    "scroll",
    "get_clipboard",
    "set_clipboard",
    "show_notification",
    "speak_text",
    "tts",
    "image_info",
    "image",
    "extract_pdf_text",
    "pdf",
}
